const Database = require('better-sqlite3');
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const path = require('path');
const db = new Database(path.join(__dirname, 'ayush.db'));
db.pragma('foreign_keys = ON');
const hash = bcrypt.hashSync('password123', 10);
const now = new Date().toISOString();
function uid() { return uuidv4(); }
const iu = db.prepare('INSERT OR IGNORE INTO users (id,email,password_hash,full_name,role,approved,assigned_admin_id,assigned_doctor_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)');
const rahul=uid(),neha=uid(),rajesh=uid(),meera=uid(),priya=uid(),amit=uid(),swati=uid(),arjun=uid(),fatima=uid(),ravi=uid(),pooja=uid(),vikram=uid();
iu.run(rahul,'rahulpd1712@gmail.com',bcrypt.hashSync('RahulAdmin123!',10),'Rahul','super_admin',1,null,null,now);
iu.run(neha,'admin.neha@ayush.com',hash,'Neha Verma','admin',1,null,null,now);
iu.run(rajesh,'admin.rajesh@ayush.com',hash,'Rajesh Kumar','admin',1,null,null,now);
iu.run(meera,'admin.meera@ayush.com',hash,'Meera Singh','admin',1,null,null,now);
iu.run(priya,'dr.priya@ayush.com',hash,'Dr. Priya Sharma','doctor',1,neha,null,now);
iu.run(amit,'dr.amit@ayush.com',hash,'Dr. Amit Gupta','doctor',1,neha,null,now);
iu.run(swati,'dr.swati@ayush.com',hash,'Dr. Swati Reddy','doctor',1,rajesh,null,now);
iu.run(arjun,'dr.arjun@ayush.com',hash,'Dr. Arjun Patel','doctor',1,rajesh,null,now);
iu.run(fatima,'dr.fatima@ayush.com',hash,'Dr. Fatima Khan','doctor',1,meera,null,now);
iu.run(ravi,'asst.ravi@ayush.com',hash,'Ravi Kumar','assistant',1,null,priya,now);
iu.run(pooja,'asst.pooja@ayush.com',hash,'Pooja Devi','assistant',1,null,amit,now);
iu.run(vikram,'asst.vikram@ayush.com',hash,'Vikram Joshi','assistant',1,null,swati,now);
const ip = db.prepare('INSERT OR IGNORE INTO patients (id,name,age,gender,contact,abha_id,created_at) VALUES (?,?,?,?,?,?,?)');
const pp=[];for(var i=0;i<12;i++)pp.push(uid());
var nm=['Sunita Devi','Amitabh Verma','Priyanka Joshi','Rahul Singh','Meena Kumari','Vijay Patel','Sita Sharma','Ravi Shankar','Anjali Gupta','Dinesh Nair','Kavita Reddy','Mohammed Irfan'];
var ag=[45,62,28,35,50,40,55,30,43,55,38,48];
var gd=['Female','Male','Female','Male','Female','Male','Female','Male','Female','Male','Female','Male'];
for(var i=0;i<12;i++)ip.run(pp[i],nm[i],ag[i],gd[i],String(9876543210+i),null,now);
var ic = db.prepare('INSERT OR IGNORE INTO cases (id,patient_id,doctor_id,stream,chief_complaints,history_present_illness,diagnosis,treatment_plan,personal_history,vitals,stream_specific_data,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)');
var cs=[[pp[0],priya,'ayurveda','Chronic knee pain for 6 months','Bilateral knee pain, worse in cold weather.','Sandhivata (Osteoarthritis)','Punarnavadi kashayam 15ml TID',-12],[pp[1],priya,'ayurveda','Menstrual irregularity for 8 months','Irregular periods, severe cramps.','Yonivyapad (Menstrual Disorder)','Ashokarishta 15ml BD',-3],[pp[2],amit,'homeopathy','Recurrent allergic rhinitis for 2 years','Sneezing bouts of 10-15 in morning.','Allergic Rhinitis','Natrum Mur 30C',-11],[pp[3],amit,'homeopathy','Migraine with aura for 5 years','Throbbing headache left side.','Migraine with Aura','Belladonna 30C',-9],[pp[4],swati,'unani','Chronic eczema for 1 year','Persistent itchy rash on forearms.','Ekhtilab-e-Bahri (Eczema)','Sharbat-e-Unjabin 20ml BD',-10],[pp[5],swati,'unani','Chronic bronchitis for 3 years','Productive cough with yellowish sputum.','Sual-e-Muzmin (Chronic Bronchitis)','Joshanda 200ml daily',-8],[pp[6],arjun,'siddha','Type 2 diabetes for 4 years','Elevated blood sugar, polyuria.','Prameham (Diabetes)','Siddha medicine + Metformin',-6],[pp[7],fatima,'ayurveda','Chronic cough for 2 months','Dry cough with minimal expectoration.','Kasa (Chronic Cough)','Sitopaladi churna 1g TID',-8],[pp[8],fatima,'ayurveda','Joint stiffness and swelling in hands','Morning stiffness lasting 1 hour.','Amavata (Rheumatoid Arthritis)','Guggulu Tiktaka kashayam 15ml BD',-4],[pp[9],priya,'ayurveda','Weight gain and sluggish metabolism','Gained 10kg over 2 years.','Sthoulya (Obesity)','Triphala churna 5g at bedtime',-3],[pp[10],amit,'homeopathy','Chronic insomnia for 1 year','Difficulty falling asleep, wakes 3-4 times.','Insomnia','Coffea Cruda 30C',-2],[pp[11],swati,'unani','Recurring headache for 6 months','Bilateral pressing headache.','Suda (Headache)','Naushadar 250mg TID',-1],[pp[0],arjun,'siddha','Chronic fatigue and weakness','Persistent tiredness despite sleep.','Oorenmai (Chronic Fatigue)','Araguine 500mg BD',-0.5],[pp[3],fatima,'ayurveda','Skin rash and itching for 2 months','Erythematous papular rash on trunk.','Kushtha (Dermatitis)','Mahamanjistadi kashayam 15ml BD',-5],[pp[5],arjun,'siddha','Acid reflux for 6 months','Heartburn after meals, worse at night.','Pitha Piravi (Acid Reflux)','Siddha antacid + lifestyle changes',-7],[pp[8],swati,'unani','High cholesterol and fatty liver','Diagnosed during routine checkup.','Su-e-Fuad (Fatty Liver)','Sharbat-e-Bazar 20ml BD',-7],[pp[4],amit,'homeopathy','Chronic urticaria for 6 months','Recurrent hives worse at night.','Chronic Urticaria','Urtica Urens 30C',-3]];
cs.forEach(function(c){ic.run(uid(),c[0],c[1],c[2],c[3],c[4],c[5],c[6],null,null,null,new Date(Date.now()+c[7]*86400000).toISOString());});
var ir = db.prepare('INSERT OR IGNORE INTO assignment_requests (id,from_user_id,to_user_id,request_type,status,reason,created_at) VALUES (?,?,?,?,?,?,?)');
ir.run(uid(),fatima,rajesh,'doctor_to_admin','pending','I want to work under Rajesh Kumar',new Date(Date.now()-86400000).toISOString());
console.log('Users:',db.prepare('SELECT count(*) as c FROM users').get().c);
console.log('Patients:',db.prepare('SELECT count(*) as c FROM patients').get().c);
console.log('Cases:',db.prepare('SELECT count(*) as c FROM cases').get().c);
db.close();
